on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose The environment:"
        required: true
        type: choice
        default: Stagging
        options:
          - Stagging
          - Production

jobs:
  run-manual-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Print Welcome Message
      run : echo "Welcome from manual workflow on ${{ inputs.environment }}."