on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Test First Job
      run: echo "${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - name: Test Second Job
      run: echo "${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: [ job_1, job_2 ]
    steps:
    - name: Test Third Job
      run: echo "${{ github.job }}"
